TebLocalPlannerROS:

    max_vel_x: 0.5
    max_vel_theta: 0.5

    acc_lim_theta: 2
    acc_lim_x: 2
    acc_lim_y: 2
    
    yaw_goal_tolerance: 0.01
    xy_goal_tolerance: 0.01

    holonomic_robot: false

    global_plan_viapoint_sep: 0.1