# AUTHOR: Neset Unver Akmandor (NUA)
# E-MAIL: akmandor.n@northeastern.edu

dummy_goal_pos_x: 0.0
dummy_goal_pos_y: 0.0
dummy_goal_pos_z: 1.0

dummy_goal_ori_r: 0.0
dummy_goal_ori_p: 0.0
dummy_goal_ori_y: 0.0
