ocs2_log_path: "dataset/ocs2/"
option: 0

## OPTION 0: Read the log
ocs2_log_name: "tmp2/20230804_145959.json"

## OPTION 1: Read the folder of logs
ocs2_log_folder_name: "tmp2"

n_round_digit: 2
joint_arm_limit_min: []
joint_arm_limit_max: []