#### Mobiman Framework Parameters

### Simulator:
# gazebo
# igibson
sim: "gazebo"

flag_gazebo: true
flag_robot: true
flag_conveyor: false
flag_bin: false
flag_pedsim: false
flag_moveit: false
flag_drl: false

### Rviz:
flag_rviz: true

# rviz/gazebo/mobile_manipulator_ocs2_gazebo
# rviz/igibson/mobile_manipulator_ocs2_igibson
rviz_config_path: "rviz/gazebo/mobile_manipulator_ocs2_gazebo"

### Map Server:
flag_map_server: true
config_map_server: "config_map_server"

### Robot:
robot_name: "jackalJaco"
n_robot: 0
robot_frame_name: "base_link"
urdf_path: "urdf/jackal_jaco.urdf"
urdf_path_ocs2: "urdf/jackal_fixedWheel_jaco_fixedFinger.urdf"    ## NUA NOTE: DEPRECATE THIS!
lib_path: "codegen/auto_generated/jackalJaco"
collision_points_config_path: "config/config_points_on_robot"

### Goal Server:
flag_goal_server: true

### Distance Server:
flag_distance_server: true
config_distance_server: "config_distance_server"

### Mobiman:
flag_mobiman: true

# task_jackalJaco_gazebo
# task_jackalJaco_igibson
task_config_path: config/task/task_jackalJaco_gazebo.info

config_mobiman_drl: "drl/config_mobiman_drl"