# AUTHOR: Neset Unver Akmandor (NUA)
# E-MAIL: akmandor.n@northeastern.edu

world_frame_name: "world"

#obj_octomap_names: ["oct_conveyor", "oct_actor0", "oct_actor1"]
#mobiman_occ_obs_names: ["conveyor_belt", "red_cube", "oct_actor0", "oct_actor1"]