# AUTHOR: Neset Unver Akmandor (NUA)
# E-MAIL: akmandor.n@northeastern.edu

trajectory_data_path: ""

trajectory_sampling_dataset_path: "dataset/trajectory_sampling/jaco/"

tss_robot_frame_name: "base_link"

# geometric
# kinematic
trajectory_gen_type: "geometric"

## Geometric Parameters ~~~~ 
# cone
# cube
geo_type: "cube"

## Cone Parameters ~~~~ 
#tlen: 0.0
#tyaw: 0.9       # rad
#tpitch: 0.6     # rad
#tyaw_cnt: 21
#tpitch_cnt: 11
#tsamp_cnt: 3

## Cube Parameters ~~~~ 
x_min: 
x_max:
x_cnt:

y_min:
y_max:
y_cnt:

z_min:
z_max:
z_cnt: 
## ~~~~~~~~~~~~~~~~~~~~~~~~~

## Kinematic Parameters ~~~~
#tsamp_cnt: 3
#dt: 0.01
#ttime: 3
#lat_velo_samp_cnt: 2
#ang_velo_samp_cnt: 15
#min_lat_velo: -1.0
#max_lat_velo: 1.0
#max_yaw_velo: 1.0
#sample_start_index: 0
## ~~~~~~~~~~~~~~~~~~~~~~~~~