tsdf_voxel_size: 0.1
tsdf_voxels_per_side: 16
#publish_esdf_map: true
#publish_pointclouds: true
#use_tf_transforms: true
#allow_clear: true
#update_mesh_every_n_sec: 0.05
#clear_sphere_for_planning: false
world_frame: world
collision_points: [[],[],[],[[0.0, 0.5], [0.25, 0.2], [0.5, 0.2], [0.75, 0.2], [1.0, 0.2]],[[0.0, 0.2], [0.25, 0.2], [0.5, 0.2], [0.75, 0.2], [1.0, 0.2]],[],[],[]]