#tsdf_voxel_size: 0.1
#tsdf_voxels_per_side: 16
##publish_esdf_map: true
##publish_pointclouds: true
##use_tf_transforms: true
##allow_clear: true
##update_mesh_every_n_sec: 0.05
##clear_sphere_for_planning: false
world_frame: world

#collision_points: [[],[],[],[[0.0, 0.5], [0.25, 0.2], [0.5, 0.2], [0.75, 0.2], [1.0, 0.2]],[[0.0, 0.2], [0.25, 0.2], [0.5, 0.2], [0.75, 0.2], [1.0, 0.2]],[],[],[]]
#collision_points: [[[0.0, 0.8]],[],[],[[0.0, 0.3], [0.5, 0.3], [1.0, 0.3]],[[0.0, 0.3], [0.5, 0.3], [1.0, 0.3]],[],[],[[1.0, 0.3]]]
#collision_points: [[[0.0, 0.3]],[],[],[[0.5, 0.15]],[[0.5, 0.15]],[],[],[[1.0, 0.075]]]
#collision_points: [[[0.0, 0.6]],[],[],[[0.5, 0.1]],[[0.5, 0.1]],[],[],[]]
#collision_points: [[[0.0, 0.35]],[],[],[[0.5, 0.15]],[],[],[],[]]
collision_points: [[[0.0, 0.35]],[],[],[],[],[],[],[]]