# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

jackal_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  cmd_vel_timeout: 0.25

  k_l: 0.1
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.5 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 20.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 4.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 25.0   # rad/s^2

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - ur5_shoulder_pan_joint
     - ur5_shoulder_lift_joint
     - ur5_elbow_joint
     - ur5_wrist_1_joint
     - ur5_wrist_2_joint
     - ur5_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      ur5_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      ur5_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      ur5_elbow_joint: {trajectory: 0.1, goal: 0.1}
      ur5_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      ur5_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      ur5_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - ur5_shoulder_pan_joint
     - ur5_shoulder_lift_joint
     - ur5_elbow_joint
     - ur5_wrist_1_joint
     - ur5_wrist_2_joint
     - ur5_wrist_3_joint

# Position Controllers ---------------------------------------
#x_axis_joint_position_controller:
#      type: effort_controllers/JointPositionController
#      joint: x_axis_joint
#      pid: {p: 1.0, i: 1.0, d: 10.0}
#y_axis_joint_position_controller:
#      type: effort_controllers/JointPositionController
#      joint: y_axis_joint
#      pid: {p: 1.0, i: 1.0, d: 10.0}
#theta_joint_position_controller:
#      type: effort_controllers/JointPositionController
#      joint: theta_joint
#      pid: {p: 100.0, i: 10, d: 1000.0}