## General Parameters
plot_flag: False
### "" defaults to data path
plot_path: ""

data_path: "/home/akmandor/sarvesh_drl_result/20230922_212129_PPO_mobiman/"

continue_initial: True
continue_initial_count: 0


### Sequences -1 means all, otherwise specify seperated by comma.
observation_sequences: -1
action_sequences: -1


### Window size for Rewards
window_episodic: 200
