# AUTHOR: Neset Unver Akmandor (NUA)
# E-MAIL: akmandor.n@northeastern.edu

isaac_sim_path: "/home/akmandor/.local/share/ov/pkg/isaac_sim-2022.2.1/"
planning_framework: "move_group_interface"
log_path: "dataset/drl_training_data/mobiman"

max_episode_length: 1000