#### DRL Parameters 
#### NOTE: Be sure that -> drl_service_flag: true

### Common Parameters for Training and Testing
gazebo_robot_name: "mobiman"
mode: "training"
drl_data_path: "dataset/drl/"
initial_training_path: ""

### DRL-Training Parameters
world_name: "conveyor"
deep_learning_algorithm: "PPO"
motion_planning_algorithm: "ocs2"

# Options:
# mobiman_FC             -> FC(occupancy_set + target + prev_action)
# mobiman_2DCNN_FC       -> 2DCNN(Channel: 1, Height: occupancy_set, Width: time) + FC(CNN_output + target + prev_action)
observation_space_type: "mobiman_FC"

n_robot: 1

# Options:
# JackalJaco_mobiman_drl-v0
task_and_robot_environment_name: "JackalJaco_mobiman_drl-v00"

learning_rate: 0.0002
n_steps: 1000
batch_size: 50
ent_coef: 0.001
training_timesteps: 2000
max_episode_steps: 2000

training_checkpoint_freq: 1000
plot_title: "Learning Curve"
plot_moving_average_window_size_timesteps: 20
plot_moving_average_window_size_episodes: 5

## Data and Sensors

world_frame_name: "world"

odom_msg_name: "/jackal_velocity_controller/odom"
cmd_velocity_msg_name: "/cmd_vel"
octomap_msg_name: "/octomap_scan"

goal_status_msg_name: "/goal_status"
goal_visu_msg_name: "/mobiman_goal"

#laser_size_downsampled: 90
#laser_normalize_flag: True
#laser_error_threshold: 0.1

occupancy_image_width: 64
occupancy_image_height: 64

## Algorithm: mobiman-DRL Parameters
obs_min_range: 0.25
n_obs_stack: 5
n_skip_obs_stack: 5
cit_flag: True # cit = channel is time
#n_wp: 8

## Reward:
reward_terminal_success: 8
reward_step_scale: 0.5
penalty_terminal_fail: -5
penalty_cumulative_step: -5

### DRL-Testing Parameters
max_testing_episode_timesteps: 2000
max_testing_episodes: 2
goal_status_msg: "/goal_reaching_status"