## Parameters
plot_flag: False

### "" defaults to data path
plot_path: ""

data_path: "/home/akmandor/ros_workspaces/igibson_ws/src/mobiman/mobiman_simulation/dataset/drl/20240215_143352_PPO_mobiman"

continue_initial: True
continue_initial_count: 0

### Sequences -1 means all, otherwise specify seperated by comma.
observation_sequences: "0,1,2,3"
#observation_sequences: -1

action_sequences: "0,1,2,3,4"
#action_sequences: -1

### Window size for Rewards
window_episodic: 20
