TrajectoryPlannerROS:
    max_vel_x: 0.5
    min_vel_x: 0.05
    max_vel_theta: 0.5
    min_in_place_vel_theta: 0.05

    acc_lim_theta: 2
    acc_lim_x: 2
    acc_lim_y: 2

    holonomic_robot: false
