<?xml version="1.0"?>
<robot name="conveyor_gazebo" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="prefix" value="belt" />
    <xacro:property name="parent_link" value="world" />
    <xacro:property name="x_wrt_parent" value="0.0" />
    <xacro:property name="y_wrt_parent" value="0.0" />
    <xacro:property name="z_wrt_parent" value="0.0" />
    <xacro:property name="roll_wrt_parent" value="0.0" />
    <xacro:property name="pitch_wrt_parent" value="0.0" />
    <xacro:property name="yaw_wrt_parent" value="0.0" />
    <xacro:property name="conveyor_size_x" value="10.0" />
    <xacro:property name="conveyor_size_y" value="0.5" />
    <xacro:property name="conveyor_size_z" value="0.2" />
    <xacro:property name="conveyor_pos_x" value="0.0" />
    <xacro:property name="conveyor_pos_y" value="0.0" />
    <xacro:property name="conveyor_pos_z" value="0.05" />

    <xacro:property name="PI" value="3.1415926535897931" />

    <xacro:macro name="conveyor_belt" params="prefix 
                                              parent_link 
                                              x_wrt_parent 
                                              y_wrt_parent 
                                              z_wrt_parent 
                                              roll_wrt_parent 
                                              pitch_wrt_parent 
                                              yaw_wrt_parent 
                                              conveyor_size_x 
                                              conveyor_size_y 
                                              conveyor_size_z">

        <joint name="fixed" type="fixed">
            <parent link="${parent_link}"/>
            <child link="${prefix}_visual"/>
            <origin xyz="${x_wrt_parent} ${y_wrt_parent} ${z_wrt_parent + conveyor_size_z / 2}" 
                    rpy="${roll_wrt_parent} ${pitch_wrt_parent} ${yaw_wrt_parent}" />
        </joint>

        <link name="${prefix}_visual">
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${conveyor_size_x} ${conveyor_size_y} ${conveyor_size_z}"/>
                </geometry>
            </collision>

            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <geometry>
                    <box size="${conveyor_size_x} ${conveyor_size_y} ${conveyor_size_z}"/>
                </geometry>
                <material name="purple" />
            </visual>

            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="1"/>
                <inertia
                    ixx="1.0" ixy="0.0" ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0"/>
            </inertial>
        </link>

        <link name="${prefix}_moving">
            <inertial>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
                <mass value="1"/>
                <inertia
                    ixx="1.0" ixy="0.0" ixz="0.0"
                    iyy="1.0" iyz="0.0"
                    izz="1.0"/>
            </inertial>

            <collision>
                <origin xyz="${conveyor_pos_x} ${conveyor_pos_y} ${conveyor_pos_z}" rpy="0 0 0"/>
                <geometry>
                    <box size="${conveyor_size_x} ${conveyor_size_y} ${conveyor_size_z}"/>
                </geometry>
            </collision>
        </link>

        <joint name="belt_joint" type="prismatic">
            <origin xyz="0.0 0.0 0.05" rpy="0 0 0"/>
            <parent link="${prefix}_visual"/>
            <child link="${prefix}_moving"/>
            <axis xyz="1 0 0"/>
            <limit lower="0.0" upper="1.0" effort="1000" velocity="1000"/>
        </joint>

        <gazebo>
            <plugin name="${prefix}_conveyor_plugin" filename="libROSConveyorBeltPlugin.so">
                <robot_namespace>/</robot_namespace>
                <link>${prefix}_moving</link>
                <power>0</power>
                <max_velocity>1.0</max_velocity>
            </plugin>
            <material>Gazebo/Purple</material>
        </gazebo>

    </xacro:macro>

    <link name="${parent_link}" />

    <xacro:conveyor_belt prefix="${prefix}"
                         parent_link="${parent_link}" 
                         x_wrt_parent="${x_wrt_parent}" 
                         y_wrt_parent="${y_wrt_parent}"
                         z_wrt_parent="${z_wrt_parent}"
                         roll_wrt_parent="${roll_wrt_parent}"
                         pitch_wrt_parent="${pitch_wrt_parent}"
                         yaw_wrt_parent="${yaw_wrt_parent}"
                         conveyor_size_x="${conveyor_size_x}"
                         conveyor_size_y="${conveyor_size_y}"
                         conveyor_size_z="${conveyor_size_z}" >
    </xacro:conveyor_belt>

</robot>